### PR TITLE
Fix problem with autoload psr4

### PR DESCRIPTION
**Pull request by tomascayuelas**
Hi all,

I propose this PR to fix the actual problem with the autoload section in the composer.json. The problem I think is due to 'exclude-from-classmap' property.

I remove this line, because I think that is not correct, and according to the composer documentation is useful when you want to exclude test classes or other not necessary files. I tested this using my fork repository into my project built with symfony 4.4 and works fine. Maybe this can be helpful to solve the problem related to this issue #19 

Thanks and I appreciate your comments, and I will hope that this works 😄

### CODE REVIEW

**Comment by tomascayuelas** [comment]
@LawnGnome @kneitinger When you have a moment please, thanks!

**Comment by kneitinger** [comment]
@tomascayuelas Thanks for opening this PR!

We had added the `"exclude-from-classmap"` entries allow for

**Comment by kneitinger** [comment]
@tomascayuelas Thank you for opening this PR, I'm glad it works for you, and I would love a solution that removes this entry in `composer.json`!

I want to take some care in testing this across a variety of PHP/Monolog versions.  To allow this package to work on every version of PHP our agent supports, we needed to allow for compatibility with both versions 1 and 2 of the Monolog API.  We can then conditionally load classes that work with the targeted API such as in [our Handler.php](https://github.com/newrelic/newrelic-monolog-logenricher-php/blob/master/src/Handler.php#L168-L180).  My concern is that removing the exclusion will fail on PHP versions lacking type annotations when the APIv2 files are loaded.

I'm running some tests now, I'll get back to you with the results.  Thanks!

**Comment by tomascayuelas** [comment]
> @tomascayuelas Thank you for opening this PR, I'm glad it works for you, and I would love a solution that removes this entry in `composer.json`!

Yes, it is the easy way to fix this 🕺 

> I want to take some care in testing this across a variety of PHP/Monolog versions. To allow this package to work on every version of PHP our agent supports, we needed to allow for compatibility with both versions 1 and 2 of the Monolog API. We can then conditionally load classes that work with the targeted API such as in [our Handler.php](https://github.com/newrelic/newrelic-monolog-logenricher-php/blob/master/src/Handler.php#L168-L180). My concern is that removing the exclusion will fail on PHP versions lacking type annotations when the APIv2 files are loaded.

In my opinion, I think the best way to do this is not to implement in the code decisions which version to load or not. The best (in my experience) would be to implement this with versioning.

In case you want to use this library with MonologV1 you will use version 1.0 of this library in case you want to use the version of MonologV2 you would use version 2.0 or whatever. 

This way we avoid delegating the responsibility to the code to make loading decisions, and therefore this also influences the simplified code, testing, maintenance, etc... Otherwise I think the code may be more difficult to maintain, test, and evolve.

> I'm running some tests now, I'll get back to you with the results. Thanks!

Ok, thanks!

**Comment by MattKetmo** [comment]
Hello, any news on this? I ran into same autoloading issue.

When running with the option `composer install --classmap-authoritative`:
```
Deprecation Notice: Class NewRelic\Monolog\Enricher\AbstractFormatter located in ./vendor/newrelic/monolog-enricher/src/Formatter.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class NewRelic\Monolog\Enricher\AbstractHandler located in ./vendor/newrelic/monolog-enricher/src/Handler.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

Which then leads to error:
```
PHP Fatal error:  Uncaught Error: Class 'NewRelic\Monolog\Enricher\Handler' not found
```

**Comment by awons** [comment]
We just ran into this issue today. For now we will just disable `--classmap-authoritative` from composer and use version <2.
In a long run I agree with @tomascayuelas - splitting this lib into two different versions would probably be the best solution.

**Comment by cjunge-work** [comment]
I think there could be an issue with how the generated classmap is built - the same class in different files will end up with one overwriting the other.

The classes in `api1` & `api2` have the same names, which composer uses to generate the classmap. It may well be that the api1 handler & formatter are forwards-compatible with monolog 2, and still works.

I think splitting the adapter part might be the only solution, allowing a v1 and v2 adapter to be loaded depending on the version of Monolog.

**Comment by josemiguelq** [comment]
@pyohannes can you review it please?

**Comment by whobutsb** [comment]
Bump for a review.

**Comment by zsistla** [comment]
Many thanks for your engagement in addressing this issue!
This has been merged as part of a larger PR and should be coming out in release 2.0.0.
Please follow issue #19 for release updates.

**Pull request closed without merging**
