### PR TITLE
Monolog V2 only version which does work with PSR4 autoloading (and therefore composer 2)

### PR DESCRIPTION
**Pull request by Tjeerd**
Although the diff looks quite large, the fix is actually quite simple:

* I renamed the files to match the actual classnames
* I moved the v2 files to the main src dir
* And removed the dynamic include of these files

### CODE REVIEW

**Comment by kneitinger** [comment]
Hi @Tjeerd, thank you for this PR! From what I can tell, this looks great.  Given how fundamental of a change this is, I'd like to do some extra validation to make sure that any and all infrastructure accounts for this new structure.  We'll get back to you early next week!

**Comment by Voziv** [comment]
Would love to see this fixed and merged. This is causing us many headaches with composer 2

**Review by zsistla — APPROVED** [review]

**Comment by zsistla** [comment]
This PR needed to be merged via CLI according to github instructions:

```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b ibuildingsnl-master master
git pull https://github.com/ibuildingsnl/newrelic-monolog-logenricher-php.git master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff ibuildingsnl-master
git push origin master
```

And has now been merged.

Thank you so much for you contribution and your patience!!

**Comment by Tjeerd** [comment]
👍 🥳

**Pull request closed without merging**
